version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - CELERY_BROKER_URL=
      - CELERY_RESULT_BACKEND=
    ports:
      - "5001:5000"
    command: ["python", "run.py"]

  celery_worker:
    build: .
    container_name: celery
    command: celery -A app.workers.celery worker --loglevel=info  
    environment:
      - CELERY_BROKER_URL=
      - CELERY_RESULT_BACKEND=
